var json_Municipio_Garcia_de_Hevia_Parroquia_Boca_de_GritaBoca_de_Grita_Centros_Poblados_0 = {
"type": "FeatureCollection",
"name": "Municipio_Garcia_de_Hevia_Parroquia_Boca_de_GritaBoca_de_Grita_Centros_Poblados_0",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": "1", "código": 200902.0, "código_est": 20.0, "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": 9.0, "municipio": "García de Hevia", "capital_mu": "La Fría", "código_par": 2.0, "parroquia": "Boca de Grita", "capital_pa": "Boca de Grita", "q2wHide_nombre": "Diamante", "descripció": null, "fuente": "https:\/\/github.com\/hrgz60\/Parroquias.git", "NOMBRES": "Diamante NOMBRES" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.369877321544678, 8.321329942598222 ] ] } },
{ "type": "Feature", "properties": { "id": "2", "código": 200902.0, "código_est": 20.0, "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": 9.0, "municipio": "García de Hevia", "capital_mu": "La Fría", "código_par": 2.0, "parroquia": "Boca de Grita", "capital_pa": "Boca de Grita", "q2wHide_nombre": "BOCA DE GRITA", "descripció": "Capital Parroquia", "fuente": "https:\/\/github.com\/hrgz60\/Parroquias.git", "NOMBRES": "Boca De Grita NOMBRES" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.399018048446862, 8.366897581619634 ] ] } },
{ "type": "Feature", "properties": { "id": "3", "código": 200902.0, "código_est": 20.0, "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": 9.0, "municipio": "García de Hevia", "capital_mu": "La Fría", "código_par": 2.0, "parroquia": "Boca de Grita", "capital_pa": "Boca de Grita", "q2wHide_nombre": "El Pueblito", "descripció": null, "fuente": "https:\/\/github.com\/hrgz60\/Parroquias.git", "NOMBRES": "El Pueblito NOMBRES" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.39655105270063, 8.387181639836026 ] ] } },
{ "type": "Feature", "properties": { "id": "4", "código": 200902.0, "código_est": 20.0, "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": 9.0, "municipio": "García de Hevia", "capital_mu": "La Fría", "código_par": 2.0, "parroquia": "Boca de Grita", "capital_pa": "Boca de Grita", "q2wHide_nombre": "Vuelta del Mono", "descripció": null, "fuente": "https:\/\/github.com\/hrgz60\/Parroquias.git", "NOMBRES": "Vuelta Del Mono NOMBRES" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.359911713612917, 8.424194197671667 ] ] } }
]
}
